
companies = frozenset(
    [
        "Airbnb",
        "Asana",
        "Atlassian",
        "Auth0",
        "AWS",
        "Babbel",
        "Badoo",
        "Baidu Research",
        "Base Lab",
        "Benchling",
        "BlackRock",
        "Blender",
        "Booking.com",
        "Canva",
        "Cloudera",
        "Cloudflare",
        "CockroachDB",
        "Coinbase",
        "Confluent",
        "Credit Karma",
        "Databricks",
        "DigitalOcean",
        "Discord",
        "Docker",
        "DoorDash",
        "Dropbox",
        "Ebay",
        "Eharmony",
        "Elastic",
        "Envato",
        "Erlang Solutions",
        "Etsy",
        "Eventbrite",
        "Evernote",
        "Expedia",
        "Facebook",
        "Facebook AI Research",
        "Feedzai",
        "Flickr",
        "Foursquare",
        "GIPHY",
        "GitHub",
        "GoCardless",
        "GoDaddy",
        "Google Online Security",
        "Google Research",
        "GoSquared",
        "GO-JEK",
        "Grab",
        "Grafana",
        "Grammarly",
        "Groupon",
        "Guardian",
        "Gusto",
        "HackerEarth",
        "HashiCorp",
        "Heroku",
        "Hootsuite",
        "Hostinger",
        "Housing.com",
        "HubSpot",
        "IBM developerWorks",
        "Imgur",
        "Indeed",
        "Instacart",
        "Instagram",
        "Intel",
        "Jane Street",
        "Khan Academy",
        "Kickstarter",
        "LINE",
        "LinkedIn",
        "Lyft",
        "Medium",
        "Microsoft Python Engineering",
        "Mozilla Automation Team",
        "Mozilla Hacks",
        "Mozilla Release Engineering",
        "Netflix",
        "New York Times",
        "Nextdoor",
        "NPR Apps",
        "Nvidia",
        "Okta",
        "Paypal",
        "Pinterest",
        "Pivotal",
        "Pluralsight",
        "Postman",
        "Postmark",
        "Postmates",
        "Prezi",
        "Quora",
        "RapidAPI",
        "Reddit",
        "Red Hat",
        "Salesforce",
        "Shazam",
        "Shopify",
        "Skyscanner",
        "Slack",
        "SlideShare",
        "Soundcloud",
        "Spotify",
        "Square",
        "Squarespace",
        "Stack Overflow",
        "Stackshare",
        "Stitch Fix",
        "Stripe",
        "SurveyMonkey",
        "Target",
        "TaskRabbit",
        "Thumbtack",
        "Tinder",
        "Toptal",
        "Transferwise",
        "TripAdvisor",
        "Trivago",
        "TrueCar",
        "Tumblr",
        "Twilio",
        "Twitter",
        "Twitch",
        "Uber",
        "Venmo",
        "Vevo",
        "WalmartLabs",
        "Wealthfront",
        "WePay",
        "Wonga Technology",
        "WyeWorks",
        "XING",
        "Yahoo",
        "Yammer",
        "Yelp",
        "YLD!",
        "Zalando",
        "Zapier",
        "Zendesk",
        "Zillow",
    ]
)